version: '3.8'

services:
  #API HATEWAY KONG
  kong-gateway:
    image: kong:latest
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yaml"
      
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      
      KONG_STATUS_LISTEN: "0.0.0.0:8002"

    ports:
      # 80:8000 -> Mapea el puerto 80 (público) al puerto proxy (8000)
      - "80:8000" 
      # 8001:8001 -> Mapea el puerto 8001 (Admin) para que lo uses tú
      - "8001:8001" 

    volumes:
      - ./APIGateway/kong.yaml:/etc/kong/kong.yaml

    networks:
      - sge-network
    depends_on:
      servicio-autenticacion:
        condition: service_healthy
      servicio-usuarios:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/status"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  #DB
  db-sge:
    image: mariadb:latest
    container_name: db-sge
    environment:
      MARIADB_ROOT_PASSWORD: "al.22825"

      MARIADB_DATABASE: "servicio_usuarios"
      MARIADB_USER: "fastapi_user"
      MARIADB_PASSWORD: "12345"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sge-network
    healthcheck:

      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p\"$$MARIADB_ROOT_PASSWORD\""]
      interval: 5s
      timeout: 5s
      retries: 10

      start_period: 20s

  #MICROSERVICIOS
  servicio-autenticacion:
    build:
      context: ./backend/ServicioAutenticacion
    container_name: servicio-autenticacion
    networks:
      - sge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/docs"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  servicio-usuarios:
    build:
      context: ./backend/ServicioUsuarios
    container_name: servicio-usuarios
    depends_on:
      db-sge:
        condition: service_healthy
    environment:


      DB_HOST: "db-sge"
      DB_USER: "fastapi_user"
      DB_PASSWORD: "12345"
      DB_NAME: "servicio_usuarios"
    networks:
      - sge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/docs"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  sge-network:
    driver: bridge

volumes:
  db_data:
