name: mobile_app
description: "A new Flutter project for employee management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  local_auth: ^2.1.8
  flutter_svg: ^2.0.10
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
